// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Task.Models;

namespace Test_Task.Migrations
{
    [DbContext(typeof(Test_TaskContext))]
    [Migration("20200329170632_Include_Check")]
    partial class Include_Check
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test_Task.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(60);

                    b.Property<bool>("Q1");

                    b.Property<bool>("Q10");

                    b.Property<bool>("Q2");

                    b.Property<bool>("Q3");

                    b.Property<bool>("Q4");

                    b.Property<bool>("Q5");

                    b.Property<bool>("Q6");

                    b.Property<bool>("Q7");

                    b.Property<bool>("Q8");

                    b.Property<bool>("Q9");

                    b.Property<double>("Sum");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
